[project]
name = "schedulease"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "hjson>=3.1.0",
    "httpx>=0.28.1",
    "lxml>=6.0.0",
    "pathlib>=1.0.1",
]
